#pragma config(Sensor, dgtl1,  leftSensor,     sensorDigitalIn)
#pragma config(Sensor, dgtl2,  rightSensor,    sensorDigitalIn)
#pragma config(Sensor, dgtl3,  stopSensor,     sensorDigitalIn)
#pragma config(Sensor, dgtl7,  ,               sensorDigitalIn)
#pragma config(Motor,  port2,           motorLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           sizeChange,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           autobox,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           forkliftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           motorRight,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Control List

Ch3 - Left motor
Ch2 - Right motor
Btn6U - Forklift up
Btn6D - Forklift down
Btn5U - Autobox up
Btn5D - Autobox down
Btn8D - Open/Close Claw
Btn8L - Extend to full size (Exit compliance size)
Btn7R - Start autonomous brain biopsy
Btn7L - Cancel autonomous brain biopsy
*/

task main(){
	bool autonomous = false;
	bool lastpress8D = false;
	bool clawOpen = true;

	string intAsString = "";
	int intToConvert = 0;


	// Move servo to fit in competition dimensions
	motor[sizeChange]=127;

	while (true){

		// If value is 0 IR is detected
		intToConvert = SensorValue[leftSensor];
		sprintf(intAsString, "%d", intToConvert);
		writeDebugStream("Left: ");
		writeDebugStreamLine(intAsString);

		intToConvert = SensorValue[rightSensor];
		sprintf(intAsString, "%d", intToConvert);
		writeDebugStream("Right: ");
		writeDebugStreamLine(intAsString);

		if (autonomous){
			if(vexRT[Btn7L]){
				// Cancel autonomous
				autonomous = false;
			}

			// Drive when the left motor sees the floor
			if (SensorValue[leftSensor] == 0){
				motor[motorLeft] = 64;
			}
			else {
				motor[motorLeft] = 0;
			}

			// Drive when the right motor sees the floor
			if (SensorValue[rightSensor] == 0){
				motor[motorRight] = 64;
			}
			else {
				motor[motorRight] = 0;
			}

			// Stop sensor
			if (SensorValue[stopSensor] == 0){
				autonomous = false;
			}

		}
		// Manual Controls
		else{
			if(vexRT[Btn7R]){
				autonomous = true;
			}
			// Expand to full size
			if(vexRT[Btn8L]){
				motor[sizeChange]=-127;
			}

			// Drive motor controls
			motor[motorLeft]=vexRT[Ch3];
			motor[motorRight]=vexRT[Ch2];

			// Forklift controls
			if(vexRT[Btn6U]){
				motor[forkliftMotor]=127;
			}
			else if(vexRT[Btn6D]){
				motor[forkliftMotor]=-127;

			}
			else{
				motor[forkliftMotor]=0;
			}

			// Move autobox platform
			if(vexRT[Btn5U]){
				motor[autobox]=127;
			}
			else if(vexRT[Btn5D]){
				motor[autobox]=-127;
			}
			else{
				motor[autobox]=0;
			}

			if(vexRT[Btn8D]){
				// Check if button is already being pressed
				if(lastpress8D==false){
					// Triggers once on button press
					// If claw is open, close it. If claw is close, open it.
					if(clawOpen){
						motor[claw]=127;
						clawOpen = false;
					}
					else{
						motor[claw]=-127;
						clawOpen = true;
					}
				}
				// Set button to pressed
				lastpress8D=true;
			}
			else{
				// Set button to unpressed
				lastpress8D=false;
			}

		}
	}
}
